[book]
title = "Annotation Guideline"
authors = ["dritter"]
language = "en"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/DanielRitter96/DanielRitter96.github.io"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/DanielRitter96/DanielRitter96.github.io/edit/main/{path}"

# CSS and JS files are imported in the order they are listed here!
additional-css = [
    "./theme/css/colors.css",
    "./theme/css/tables.css",
    "./theme/css/misc.css",
]

additional-js = [
    "./theme/js/papaparse.min.js",
]

# currently incompatible
# [output.linkcheck]
# optional = true